export class Decfiscmens {
   
    userId: string;
    email: string;
    _id:string;
    registrecommerce:string;
    matriculefiscale:string;
    codetva:string;
    codegenre:string;
    raisonsociale:string;
    adresse:string;
    codepostal:string;
    activite:string;
datearretactivite:string;

    firstname:string;
    lastname:string;
    codedeclaration:string;
    mois:string;
    annee:string;
    
    created:Date;
    
  updated: Date;

  impottype1: {
statut:string;
motif:string;
type:string;
traitementetsalaire:{
salairebrut:string;
salaireimposable:string;
retenuealasource:string;
contributionsociale:string;
}
location1:{
    type:string;
    montantbrut:string;
    taux:string;
    montantnet:string;
    montantretenue:string;
}
location2:{
    type:string;
    montantbrut:string;
    taux:string;
    montantnet:string;
    montantretenue:string;
}
location3:{
    type:string;
    montantbrut:string;
    taux:string;
    montantnet:string;
    montantretenue:string;
}
location4:{
    type:string;
    montantbrut:string;
    taux:string;
    montantnet:string;
    montantretenue:string;
}
honoraire1:{
    type:string;
    montantbrut:string;
    taux:string;
    montantnet:string;
    montantretenue:string;
}
honoraire2:{
    type:string;
    montantbrut:string;
    taux:string;
    montantnet:string;
    montantretenue:string;
}
honoraire3:{
    type:string;
    montantbrut:string;
    taux:string;
    montantnet:string;
    montantretenue:string;
}
montant10001:{
    type:string;
    montantbrut:string;
    taux:string;
    montantnet:string;
    montantretenue:string;
}
montant10002:{
    type:string;
    montantbrut:string;
    taux:string;
    montantnet:string;
    montantretenue:string;
}
montant10003:{
    type:string;
    montantbrut:string;
    taux:string;
    montantnet:string;
    montantretenue:string;
}
montant10004:{
    type:string;
    montantbrut:string;
    taux:string;
    montantnet:string;
    montantretenue:string;
}
autre:{
    titre:string;
    montant:string;
    description:string;
}
  }
      
    }